// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as dotenv from "dotenv";
import { resolve } from "path";

// Load .env.local first for local overrides, then .env
dotenv.config({ path: resolve(process.cwd(), ".env.local") });
dotenv.config();

import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts"
  },
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
